// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://psbtshibrbenojdnutdd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzYnRzaGlicmJlbm9qZG51dGRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NTAzMjYsImV4cCI6MjA2NjQyNjMyNn0.j58DcHkZ-z4KlJuX3Lt6TtnFSGOhgNPznmfD11SZwko";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);